### ISSUE TITLE
It does not correspond to yescrypt.

### ISSUE THREAD

**Issue by jagaricoin-project** [nasa8x/node-genesis-block#10]
Hi,
Thank you for publishing wonderful software.
I prepared the environment and made it possible to generate Genesis block

However, it did not seem to correspond to the following algorithm.
scrypt: error
yescrypt: There is no Symbol
*It corresponded to neoscrypt.

Do you deal with yescrypt in the future?

Thanks in advance.

**Comment by nasa8x** [comment]
Done:

> cd genesis-block
> npm update
> node genesis -a yescrypt

**Comment by jagaricoin-project** [comment]
Thank you for your reply.
Unfortunately mnp update did not solve it.
I tried various updates, but updete itself fails.
We would appreciate it if you fix the multi-hashing source.

@ubuntu:~/genesis-block$ node genesis -a yescrypt
---------------
algorithm: yescrypt
pzTimestamp: Don't work for weekends, work for our goals.
pubkey: 04678afdb0fe5548271967f1~~~
bits: 504365040
time: 1522935268
merkle root hash: f5239467dd2a9dd~~~
Searching for genesis hash...
node: symbol lookup error: /home/genesis-block/node_modules/multi-hashing/build/Release/multihashing.node: undefined symbol: yescrypt_hash

Thanks.

**Comment by watch-activity** [comment]
Hi,
I modified the source so that I can start it.
However, because the source itself is incomplete, it was not possible to create the origin block of yescrypt.
Also, some algorithms seem to be incomplete.

**Comment by jagaricoin-project** [comment]
I modified the source so that I can start it.
However, because the source itself is incomplete, it was not possible to create the origin block of yescrypt.
Also, some algorithms seem to be incomplete.

**Comment by nasa8x** [comment]
```
node genesis -a yescrypt
---------------
algorithm: yescrypt
pzTimestamp: Don't work for weekends, work for our goals.
pubkey: 04678afdb0fe5548271967f1a67130b7105cd6a828e03909a67962e0ea1f61deb649f6bc3f4cef38c4f35504e51ec112de5c384df7ba0b8d578a4c702b6bf11d5f
bits: 504365040
time: 1523260088
merkle root hash: f5239467dd2a9dd0fce7a3babc03c7985eab2229c62e3d5670375f305753c9cc
Searching for genesis hash...
nonce: 28668
genesis hash: 0000f4fd709ca34324ebf1706080e2bdc5228b309c5b2fed6b1b6b8caf86a8e4
```

**Comment by jagaricoin-project** [comment]
Thank you for responding to the correction!
I confirmed that the code works.
I appreciate quick response!
