### ISSUE TITLE
CMainParams::CMainParams(): Assertion `hashGenesisBlock == uint256("0x000006bcac49f818e6bb484ee4cbad7aba72563e183decfd4391b4847ffd1cae")' failed.

### ISSUE THREAD

**Issue by phantanthanh1996** [nasa8x/node-genesis-block#3]
Hi sir, I try to use with quark to create genesis block for pivx-clone. but when i start daemon i receive error that:
CMainParams::CMainParams(): Assertion `hashGenesisBlock == uint256("0x000006bcac49f818e6bb484ee4cbad7aba72563e183decfd4391b4847ffd1cae")' failed.
Pls help me :( :(

**Comment by nasa8x** [comment]
Please add more info. What's your genesis params?
The genesis block information must match your coin parameters.
